### ISSUE TITLE
On mobile, you can't switch the leaderboard season

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/ZeSS#106]
![Screenshot_20241029-234248_Firefox](https://github.com/user-attachments/assets/28e35465-4fee-48cb-8383-14150c2b0b42)

**Comment by Topvennie** [comment]
On somewhat wider phones you can still select the season in the navbar. Making it accessible on look somewhat nice smaller phones was a pain in the butt so I removed it.

In any case you can always navigate to the settings menu and select the desired season there. (I just noticed the settings layout needs some adjustments on mobile). You can go to the settings page by pressing the profile icon in the top right corner.

**Comment by Topvennie** [comment]
Closing it as it's not something I plan on adding back myself.
However feel free to open a PR to add the selector back to the navbar for small phones.
