### ISSUE TITLE
vingo: POST /scans no longer returns the username

### ISSUE THREAD

**Issue by Reavershark** [ZeusWPI/ZeSS#77]
When POSTing to /api/scans from vinscant, we get a 200 with an empty body (content-length: 0) on success.
We used to get the name of the card holder so we could display that name on e.g. leddy.

Hannes fix pls ! ty

**Comment by Topvennie** [comment]
Another feature that has disappeared :O

**Comment by Topvennie** [comment]
What a shame

**Comment by hannes-dev** [comment]
This will be fixed when the live service is migrated to the new backend
